name: Finish release
on:
  workflow_dispatch:
    inputs:
      versionName:
        type: string
        required: true
  repository_dispatch:
    types: [finish_release]
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ inputs.versionName || github.event.client_payload.version }}
  publish_cocoapods:
    uses: ./.github/workflows/support_pods.yaml
    secrets: inherit
    needs: create_tag
