name: Push main lib podspec
on:
  workflow_dispatch:
    inputs:
  workflow_call:
    inputs:
      branch:
        type: string
jobs:
  push:
    runs-on: [ macOS-latest ]
    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ inputs.branch }}
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod repo update
        pod trunk push PaltaAnalytics.podspec --allow-warnings
