name: Start release
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Semantic version name'
        required: true
        type: string
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'release/${{ github.event.inputs.versionName }}'
  set-version-number:
    uses: ./.github/workflows/set_version.yaml
    secrets: inherit
    needs: create-release-branch
    with:
      version: ${{ github.event.inputs.versionName }}
      branch: 'release/${{ github.event.inputs.versionName }}'
  launch-e2e-tests:
    uses: ./.github/workflows/start_e2e_test.yaml
    secrets: inherit
    needs: set-version-number
    with:
      version: ${{ github.event.inputs.versionName }}
      branch: 'release/${{ github.event.inputs.versionName }}'
      nextAction: finish_release
      
    
