name: Push supporting podspecs
on:
  workflow_dispatch:
    inputs:
    
jobs:
  push:
    runs-on: [ macOS-latest ]
    steps:
    - uses: actions/checkout@v1
    - name: Publish to CocoaPod register
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
      run: |
        pod trunk push PaltaAnalyticsWiring.podspec --allow-warnings
        pod trunk push PaltaAnalyticsPrivateModel.podspec --allow-warnings
        pod trunk push PaltaAnalyticsModel.podspec --allow-warnings
    - name: Sleep for 4 min
      uses: juliangruber/sleep-action@v2.0.0
      with:
        time: 240s
  push-main:
    uses: ./.github/workflows/main_pod.yaml
    secrets: inherit
    needs: push
