name: Run unit tests
on:
  workflow_dispatch:
  workflow_call:
jobs:
  run_tests:
    runs-on: [ macOS-latest ]
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: |
        xcodebuild -scheme PaltaEventSchemaSwiftSDK-Package test -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' -xcconfig unit_tests.xcconfig


